# -*- coding: utf-8 -*-
"""sentiment_extract.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Has4FOihQ-gfsOHvkJTgpQy1MRSFwAND
"""

import tweepy
from textblob import TextBlob
from wordcloud import WordCloud
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
plt.style.use('fivethirtyeight')

import csv 
with open('Zomato_text.csv', newline='', encoding='utf-8') as file:
    
    reader = csv.reader(file)
      
    # store the headers in a separate variable,
    # move the reader object to point on the next row
    headings = next(reader)
      
    # output list to store all rows
    Text_out = []
    for row in reader:
        Text_out.append(row)

polarity=[]

for text in Text_out:
    
    new_text = str(text)[2:-2]
    
    polarity.append(TextBlob(new_text).polarity)

for sentiment in polarity:
    print (sentiment)

def getAnalysis(score):
    if score < 0:
        return 'Negative'
    elif score == 0:
        return 'Neutral'
    else: 
        return 'Positive'

analysis=[]    
for pol in polarity:
    analysis.append(getAnalysis(pol))

positive = 0;
negative = 0;
neutral = 0;
total = 0;

def count_total(analysis):
    total = 0
    for ana in analysis:
        total = total+1
        
    return total;
    
def count_positive(analysis):
    positive = 0
    for ana in analysis:
        if ana=='Positive':
            positive=positive+1
    return positive;        

def count_negative(analysis):
    negative = 0
    for ana in analysis:
        if ana=='Negative':
            negative=negative+1
    return negative;        

def count_neutral(analysis):
    neutral = 0
    for ana in analysis:
        if ana=='Neutral':
            neutral=neutral+1
    return neutral;        



positive= count_positive(analysis);
negative = count_negative(analysis);
neutral = count_neutral(analysis);
total = count_total(analysis);
print('Positive = ' + str(positive)+ ' or ' + str(round((positive/total*100),1)) + '% \n');
print('Negative = '+ str(negative) +' or ' + str(round((negative/total*100),1)) + '% \n');
print('Neutral = ' + str(neutral) + ' or ' + str(round((neutral/total*100),1)) + '% \n');
print('Total = ' + str(total) + '\n');

import pandas as pd  
  
     
# list of name, degree, score 
pol = polarity
senti = analysis 

     
# dictionary of lists  
dict = {'Polarity': pol, 'Sentiment': senti}  
       
df = pd.DataFrame(dict) 
    
# saving the dataframe 
df.to_csv('SentiZomato.csv')

